apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dreamwiseai-website-ingress
  namespace: dreamwiseai-website-frontend
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - host: dreamwiseai.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dreamwiseai-website-svc
                port:
                  number: 80
    - host: www.dreamwiseai.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dreamwiseai-website-svc
                port:
                  number: 80
