apiVersion: v1
kind: Service
metadata:
  name: dreamwiseai-website-svc
  namespace: dreamwiseai-website-frontend
spec:
  selector:
    app: dreamwiseai-website
  ports:
    - port: 80
      targetPort: 3000
  type: ClusterIP
